import { PrismaClient, OrgType, ExperienceLevel, OpportunityType, UpdateType } from '@prisma/client';
const db = new PrismaClient();

async function seed() {
  console.log('Seeding remaining data...');

  // Check existing counts
  const existingJobs = await db.job.count();
  const existingOpps = await db.opportunity.count();
  const existingArts = await db.article.count();
  const existingUpdates = await db.jobUpdate.count();
  console.log(`Existing - Jobs: ${existingJobs}, Opps: ${existingOpps}, Articles: ${existingArts}, Updates: ${existingUpdates}`);

  // Get employers for reference
  const employers = await db.employer.findMany();
  const cats = await db.category.findMany();
  const catMap = Object.fromEntries(cats.map(c => [c.slug, c.id]));
  const empMap = Object.fromEntries(employers.map((e, i) => [i, e.id]));

  // Seed OPPORTUNITIES (all 12)
  if (existingOpps === 0) {
    const opps = [
      { title: "MasterCard Foundation Scholars Program at University of Nairobi", slug: "mastercard-foundation-scholars-university-of-nairobi", type: "scholarship" as OpportunityType, providerId: null, description: "Full scholarship for economically disadvantaged but academically talented students from Kenya pursuing undergraduate or master's degrees at the University of Nairobi.", amount: null, deadline: "2026-07-15", link: "https://mastercardfdn.org" },
      { title: "DAAD Kenya Scholarships for Postgraduate Studies", slug: "daad-kenya-scholarships-postgraduate", type: "scholarship" as OpportunityType, providerId: null, description: "Funding for Kenyan students to pursue Master's or PhD degrees at German universities. Covers tuition, travel, health insurance, and monthly stipend.", amount: null, deadline: "2026-06-30", link: "https://daad.de" },
      { title: "Kenya Education Fund (KEF) Scholarships", slug: "kenya-education-fund-kef-scholarships", type: "scholarship" as OpportunityType, providerId: null, description: "Provides scholarships for bright and needy Kenyan students to attend secondary school and university. Focus on students from marginalized communities.", amount: 100000, deadline: "2026-08-01", link: null },
      { title: "Google Africa Developer Scholarship", slug: "google-africa-developer-scholarship", type: "certification" as OpportunityType, providerId: empMap[15], description: "Free access to Google Career Certificates and Pluralsight courses in Android development, cloud computing, and data analytics for African developers.", amount: 0, deadline: "2026-05-30", link: "https://developers.google.com" },
      { title: "Aga Khan Foundation International Scholarship", slug: "aga-khan-foundation-international-scholarship", type: "scholarship" as OpportunityType, providerId: null, description: "50% grant and 50% loan for outstanding students from developing countries pursuing postgraduate studies at top universities worldwide.", amount: null, deadline: "2026-09-01", link: "https://akdn.org" },
      { title: "Equity Group Foundation Wings to Fly Scholarship", slug: "equity-wings-to-fly-scholarship", type: "scholarship" as OpportunityType, providerId: empMap[1], description: "Comprehensive scholarship for academically gifted but financially disadvantaged students to attend leading high schools and universities in Kenya.", amount: null, deadline: "2026-07-15", link: "https://equitygroupfoundation.com" },
      { title: "Fulbright Foreign Student Program - Kenya", slug: "fulbright-foreign-student-program-kenya", type: "scholarship" as OpportunityType, providerId: null, description: "Full scholarships for Kenyan graduate students, young professionals, and artists to study, research, or teach in the United States for one academic year.", amount: null, deadline: "2026-10-15", link: "https://fulbright.state.gov" },
      { title: "Microsoft AI School Africa Scholarship", slug: "microsoft-ai-school-africa", type: "certification" as OpportunityType, providerId: empMap[16], description: "Free AI and machine learning training for African tech professionals. Includes access to Azure AI services and certification exam vouchers.", amount: 0, deadline: "2026-06-15", link: "https://microsoft.com/africa" },
      { title: "Safaricom Technology Academy Internship", slug: "safaricom-technology-academy-internship", type: "internship" as OpportunityType, providerId: empMap[0], description: "A 6-month intensive internship program at Safaricom's Technology Academy. Gain hands-on experience in telecommunications, software development, and network engineering.", amount: 50000, deadline: "2026-06-01", link: "https://safaricom.co.ke/about/careers" },
      { title: "County Government Bursary - Nakuru County", slug: "nakuru-county-bursary", type: "bursary" as OpportunityType, providerId: null, description: "Financial assistance for students from Nakuru County enrolled in secondary schools, colleges, and universities. Priority given to orphaned and vulnerable students.", amount: 30000, deadline: "2026-07-30", link: null },
      { title: "KCB SME Leadership Program Sponsorship", slug: "kcb-sme-leadership-program", type: "sponsorship" as OpportunityType, providerId: empMap[2], description: "KCB Group sponsors aspiring entrepreneurs to attend a 12-week leadership and business development program. Includes mentorship, networking, and seed funding opportunities.", amount: 100000, deadline: "2026-08-15", link: "https://kcbgroup.com" },
      { title: "World Vision Kenya Community Health Volunteer Training", slug: "world-vision-kenya-chv-training", type: "certification" as OpportunityType, providerId: empMap[9], description: "Free certified training for community health volunteers in partnership with the Ministry of Health. Covers maternal health, nutrition, and disease prevention.", amount: 0, deadline: "2026-07-01", link: "https://wvi.org/kenya" },
    ];

    for (const opp of opps) {
      await db.opportunity.create({
        data: {
          title: opp.title,
          slug: opp.slug,
          type: opp.type,
          providerId: opp.providerId,
          description: opp.description || null,
          amount: opp.amount,
          deadline: opp.deadline ? new Date(opp.deadline) : null,
          link: opp.link,
          isActive: true,
        }
      });
    }
    console.log(`Created ${opps.length} opportunities`);
  }

  // Seed ARTICLES (all 6)
  if (existingArts === 0) {
    const articles = [
      { title: "How to Write a Winning CV in Kenya: The Complete 2026 Guide", slug: "winning-cv-kenya-guide", excerpt: "Stand out from thousands of applicants with a professionally crafted CV tailored for the Kenyan job market. Learn the essential sections, formatting tips, and common mistakes to avoid.", content: "Your CV is your first impression with a potential employer. In Kenya's competitive job market, where a single position can attract hundreds of applications, your CV needs to be exceptional to get noticed. This comprehensive guide covers everything from choosing the right format to highlighting your achievements effectively. We will walk you through each section of a professional CV, provide examples specific to the Kenyan context, and share insider tips from recruiters at top Kenyan companies. Whether you are a fresh graduate or an experienced professional, this guide will help you create a CV that gets you noticed.\n\n## Essential CV Sections\n\n### Personal Information\nKeep this section brief and professional. Include your full name, phone number, email address, and location. Avoid unnecessary details like your ID number, religion, or marital status unless specifically requested.\n\n### Professional Summary\nThis is your elevator pitch in 2-3 sentences. Tailor it to each job application and highlight your most relevant skills and experience.\n\n### Work Experience\nList your roles in reverse chronological order. Use action verbs and quantify achievements where possible. For example: 'Led a team of 10 developers to deliver a mobile banking app that increased customer engagement by 35%.'\n\n### Education\nInclude your highest qualification first. Mention the institution, degree, and graduation year. For fresh graduates, include relevant coursework and academic achievements.\n\n### Skills\nCreate a dedicated skills section that aligns with the job description. Include both technical and soft skills.", category: "CV & Interview Tips", author: "JobReady Kenya Team" },
      { title: "Top 15 Highest Paying Jobs in Kenya for 2026", slug: "highest-paying-jobs-kenya-2026", excerpt: "Discover which careers command the highest salaries in Kenya, from tech roles to specialized medical positions. Updated salary data and industry trends for job seekers.", content: "Kenya's job market is evolving rapidly with technology driving salary growth across multiple sectors. Based on industry surveys and recruitment data, we have compiled the most comprehensive list of the highest-paying careers in Kenya for 2026.\n\n## 1. Software Architect - KSh 350,000 - 800,000/month\nSoftware architects design the overall structure of software systems. With Kenya's tech boom, demand has skyrocketed.\n\n## 2. Investment Banker - KSh 300,000 - 700,000/month\nTop investment banks in Nairobi offer some of the highest salaries, especially for professionals with CFA qualifications.\n\n## 3. Medical Specialist - KSh 250,000 - 600,000/month\nSpecialist doctors, particularly in fields like cardiology, neurology, and oncology, command premium salaries.\n\n## 4. Data Scientist - KSh 200,000 - 500,000/month\nAs companies embrace data-driven decision making, skilled data scientists are in high demand.\n\n## 5. Petroleum Engineer - KSh 200,000 - 450,000/month\nKenya's emerging oil and gas sector offers lucrative opportunities for petroleum engineers.\n\n## 6. Corporate Lawyer - KSh 180,000 - 400,000/month\nSenior corporate lawyers at top firms and in-house positions earn significantly.\n\n## 7. Pilot - KSh 200,000 - 500,000/month\nExperienced captains at Kenya Airways and other airlines earn top salaries.\n\n## 8. Product Manager - KSh 200,000 - 400,000/month\nProduct managers at tech companies and financial institutions are among the best-paid professionals.\n\n## 9. Chief Financial Officer - KSh 300,000 - 800,000/month\nCFOs at medium to large companies earn premium packages including bonuses and stock options.\n\n## 10. Cybersecurity Specialist - KSh 180,000 - 350,000/month\nWith increasing cyber threats, cybersecurity professionals command high salaries.\n\n## 11. DevOps Engineer - KSh 180,000 - 350,000/month\nCompanies transitioning to cloud infrastructure need skilled DevOps engineers.\n\n## 12. Pharmacist - KSh 100,000 - 250,000/month\nPharmacists in hospital and retail settings earn competitive salaries.\n\n## 13. Civil Engineer (Senior) - KSh 150,000 - 300,000/month\nWith Kenya's infrastructure development, senior civil engineers are well compensated.\n\n## 14. Actuary - KSh 150,000 - 300,000/month\nActuaries in insurance and financial services are among the best-paid analytical professionals.\n\n## 15. University Lecturer (Senior) - KSh 120,000 - 250,000/month\nSenior lecturers and professors with PhDs earn competitive academic salaries.", category: "Salary & Career Growth", author: "JobReady Kenya Research" },
      { title: "How to Prepare for Safaricom Job Interviews", slug: "safaricom-interview-prep", excerpt: "Insider tips for acing interviews at Kenya's most sought-after employer. Learn about their interview process, common questions, and what they look for in candidates.", content: "Safaricom is consistently ranked as one of Kenya's best employers, but their hiring process is rigorous. With over 50,000 applications monthly for various positions, understanding their interview methodology can give you a significant advantage.\n\n## Safaricom's Interview Process\n\n### Stage 1: Online Application\nYour CV and cover letter are screened by their recruitment team. Keywords from the job description matter, so tailor your application.\n\n### Stage 2: Phone Screening\nA 15-30 minute phone interview to verify your qualifications, salary expectations, and availability.\n\n### Stage 3: Technical Assessment\nFor technical roles, you will face a coding challenge or case study. Prepare by practicing on platforms like LeetCode and HackerRank.\n\n### Stage 4: Panel Interview\nUsually 2-4 interviewers including the hiring manager and team members. Expect behavioral and situational questions.\n\n### Stage 5: Final Interview\nA senior leadership interview focusing on cultural fit and long-term potential.\n\n## Common Interview Questions\n\n1. Tell me about a time you dealt with a difficult team member.\n2. How would you improve M-PESA's user experience?\n3. Describe a situation where you had to meet a tight deadline.\n4. What do you know about Safaricom's latest products and services?\n5. How do you handle failure?\n\n## What Safaricom Looks For\n- Innovation mindset\n- Customer-centric thinking\n- Collaboration skills\n- Adaptability and resilience\n- Technical competence\n- Cultural fit with their values", category: "Company Guides", author: "JobReady Kenya Team" },
      { title: "Government Job Application Guide: TSC, KRA & County Jobs", slug: "government-job-application-guide", excerpt: "Navigate the Kenyan government job application process with ease. Step-by-step instructions for TSC, KRA, county government, and public service commission applications.", content: "Government jobs in Kenya offer job security, good benefits, and career progression. However, the application process can be complex and competitive. This guide breaks down the process for various government bodies.\n\n## Teachers Service Commission (TSC)\n\n### Eligibility\n- Bachelor of Education or relevant degree\n- Must be registered with TSC\n- Valid teaching certificate\n\n### Application Process\n1. Visit the TSC online portal (teachersonline.tsc.go.ke)\n2. Create an account or log in\n3. Select the county and school type you prefer\n4. Upload required documents (certificates, TSC registration)\n5. Submit before the deadline\n\n## Kenya Revenue Authority (KRA)\n\n### Common Positions\n- Tax Assessor\n- Customs Officer\n- Internal Auditor\n- ICT Specialist\n\n### Application Tips\n- Emphasize analytical and numerical skills\n- Highlight any experience with tax or accounting\n- KRA values integrity and attention to detail\n\n## County Governments\n\n### How to Apply\n- Visit the specific county government website\n- Check the Public Service Board section for vacancies\n- Applications usually require: CV, cover letter, certified copies of certificates, and national ID\n\n## Public Service Commission (PSC)\n\n### Key Tips\n- Monitor the PSC website regularly for new vacancies\n- Ensure all documents are certified\n- Follow the application format precisely\n- Track your application status online\n\n## Important Documents to Prepare\n- National ID card\n- KRA PIN certificate\n- Certificate of Good Conduct\n- Academic and professional certificates\n- Passport-size photographs\n- Recommendation letters", category: "Government Jobs", author: "JobReady Kenya Research" },
      { title: "The Rise of Remote Work in Kenya: Opportunities & Challenges", slug: "remote-work-kenya", excerpt: "Kenya's remote work sector is booming. Learn about available opportunities, required skills, and how to position yourself for location-independent careers.", content: "The COVID-19 pandemic accelerated remote work adoption globally, and Kenya has emerged as one of Africa's leading destinations for remote talent. With improving internet infrastructure and a growing tech ecosystem, opportunities continue to expand.\n\n## The State of Remote Work in Kenya\n\nKenya's remote work market has grown by over 300% since 2020. Nairobi is now ranked among the top 5 African cities for remote work, thanks to its skilled workforce and improving digital infrastructure.\n\n## Top Remote Work Opportunities\n\n### Software Development\nKenyan developers are in high demand globally. Companies like Andela, Toptal, and remote-first startups actively recruit Kenyan tech talent with salaries ranging from $2,000 to $10,000 monthly.\n\n### Digital Marketing\nRemote marketing roles including SEO specialists, content writers, and social media managers are increasingly available.\n\n### Customer Support\nMany international companies hire Kenyan customer support agents for remote positions, offering competitive pay and flexible hours.\n\n### Virtual Assistance\nExperienced administrative professionals can find remote VA positions supporting international businesses.\n\n### Freelance Writing and Design\nPlatforms like Upwork, Fiverr, and local job boards offer numerous freelance opportunities.\n\n## Skills Needed for Remote Work\n- Self-discipline and time management\n- Excellent communication skills\n- Proficiency in collaboration tools (Slack, Zoom, Notion)\n- Technical literacy\n- Problem-solving ability\n\n## Challenges\n- Unreliable electricity in some areas\n- Time zone differences with international clients\n- Payment processing complexities\n- Self-motivation without office structure\n\n## How to Get Started\n1. Build relevant skills through online courses\n2. Create a professional online presence (LinkedIn, portfolio)\n3. Join remote work communities and job boards\n4. Start with freelance platforms to build experience\n5. Network actively in online communities", category: "Remote Work", author: "JobReady Kenya Team" },
      { title: "Scholarship Application Tips: How to Win Funding for Your Studies", slug: "scholarship-application-tips", excerpt: "Competition for scholarships in Kenya is intense. Learn proven strategies to strengthen your applications and increase your chances of securing educational funding.", content: "Thousands of scholarships are available to Kenyan students every year, but many go unclaimed because applicants do not know how to present themselves effectively. This article provides practical tips from successful scholarship recipients.\n\n## Understanding the Scholarship Landscape\n\nKenyan students can access scholarships from various sources: government (county and national), international organizations, private foundations, universities, and corporate social responsibility programs.\n\n## Top Scholarship Tips\n\n### 1. Start Early\nBegin researching scholarships at least 6 months before deadlines. Many prestigious scholarships have early closing dates and lengthy application processes.\n\n### 2. Tailor Each Application\nGeneric applications rarely succeed. Research the scholarship provider's values and mission, then align your application accordingly.\n\n### 3. Craft a Compelling Personal Statement\nYour personal statement should tell a story. Focus on:\n- Your academic journey and achievements\n- Financial need (be honest and specific)\n- Leadership experience and community involvement\n- Future goals and how the scholarship will help\n- What you will give back to the community\n\n### 4. Get Strong Recommendation Letters\nChoose recommenders who know you well and can speak to your abilities. Provide them with your CV, transcript, and the scholarship details to help them write targeted letters.\n\n### 5. Proofread Everything\nTypos and grammatical errors can cost you the scholarship. Have multiple people review your application.\n\n### 6. Highlight Leadership and Community Impact\nMost scholarship providers look for candidates who will make a positive impact. Showcase your volunteer work, leadership roles, and community initiatives.\n\n### 7. Prepare for Interviews\nSome scholarships require interviews. Practice common questions, dress professionally, and be ready to discuss your goals and motivations.\n\n### 8. Apply to Multiple Scholarships\nDo not put all your eggs in one basket. Apply to at least 5-10 scholarships to maximize your chances.\n\n### 9. Meet All Deadlines\nLate applications are automatically disqualified. Set calendar reminders and submit applications well before deadlines.\n\n### 10. Follow Up\nAfter submitting, follow up with the scholarship provider. A polite email expressing continued interest can leave a positive impression.\n\n## Scholarships to Watch\n- MasterCard Foundation Scholars Program\n- DAAD Scholarships\n- Equity Wings to Fly\n- Fulbright Program\n- Google Africa Scholarships\n- KENYA Education Fund", category: "Scholarships", author: "JobReady Kenya Team" },
    ];

    for (const art of articles) {
      await db.article.create({
        data: {
          title: art.title,
          slug: art.slug,
          excerpt: art.excerpt,
          content: art.content,
          category: art.category,
          author: art.author,
          published: true,
        }
      });
    }
    console.log(`Created ${articles.length} articles`);
  }

  console.log('Done! Checking final counts...');
  const finalJobs = await db.job.count();
  const finalOpps = await db.opportunity.count();
  const finalArts = await db.article.count();
  console.log(`Final - Jobs: ${finalJobs}, Opps: ${finalOpps}, Articles: ${finalArts}`);
  await db.$disconnect();
}

seed().catch(e => { console.error(e); process.exit(1); });
