import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const employers = [
  { name: "Safaricom PLC", logo: "SFC", industry: "Telecommunications", size: "5000+", website: "https://safaricom.co.ke", description: "Kenya's leading telecommunications company providing mobile, voice, data, and financial services.", isVerified: true },
  { name: "Equity Bank Kenya", logo: "EBK", industry: "Banking & Finance", size: "5000+", website: "https://equitybank.co.ke", description: "One of East Africa's largest banking groups with operations across the region.", isVerified: true },
  { name: "KCB Group", logo: "KCB", industry: "Banking & Finance", size: "5000+", website: "https://kcbgroup.com", description: "The largest commercial bank in Kenya with a presence in six East African countries.", isVerified: true },
  { name: "NCBA Group", logo: "NCB", industry: "Banking & Finance", size: "1000-5000", website: "https://ncbagroup.com", description: "A leading financial services group in East Africa.", isVerified: true },
  { name: "Kenya Airways", logo: "KQA", industry: "Aviation", size: "1000-5000", website: "https://kenyaairways.com", description: "The flag carrier airline of Kenya, operating flights across Africa and internationally.", isVerified: true },
  { name: "East Africa Breweries Limited", logo: "EAB", industry: "Manufacturing", size: "1000-5000", website: "https://eabl.com", description: "A leading beverage alcohol manufacturer in East Africa.", isVerified: true },
  { name: "Bidco Africa", logo: "BID", industry: "Manufacturing", size: "1000-5000", website: "https://bidcoafrica.com", description: "A leading consumer goods manufacturer specializing in edible oils, soaps, and detergents.", isVerified: true },
  { name: "Unilever Kenya", logo: "UNL", industry: "Manufacturing", size: "500-1000", website: "https://unilever.co.ke", description: "A global fast-moving consumer goods company with operations in Kenya.", isVerified: true },
  { name: "Safaricom Foundation", logo: "SFF", industry: "NGO & Non-Profit", size: "50-200", website: "https://safaricomfoundation.org", description: "Safaricom's corporate social investment arm focused on community development.", isVerified: true },
  { name: "World Vision Kenya", logo: "WVK", industry: "NGO & Non-Profit", size: "500-1000", website: "https://wvi.org/kenya", description: "An international humanitarian organization dedicated to children's welfare.", isVerified: true },
  { name: "UNICEF Kenya", logo: "UNI", industry: "NGO & Non-Profit", size: "200-500", website: "https://unicef.org/kenya", description: "The United Nations agency responsible for providing humanitarian aid to children worldwide.", isVerified: true },
  { name: "Kenya Medical Research Institute", logo: "KEM", industry: "Healthcare & Research", size: "1000-5000", website: "https://kemri.org", description: "Kenya's leading medical research institution.", isVerified: true },
  { name: "Aga Khan University Hospital", logo: "AKH", industry: "Healthcare & Research", size: "500-1000", website: "https://aku.edu", description: "A premier teaching and tertiary healthcare facility in East Africa.", isVerified: true },
  { name: "Ministry of Education", logo: "MOE", industry: "Government", size: "5000+", website: "https://education.go.ke", description: "Kenya's government ministry responsible for education policy and administration.", isVerified: true },
  { name: "Kenya Revenue Authority", logo: "KRA", industry: "Government", size: "5000+", website: "https://kra.go.ke", description: "Kenya's tax collection authority responsible for revenue mobilization.", isVerified: true },
  { name: "Google Kenya", logo: "GGK", industry: "Technology & IT", size: "50-200", website: "https://google.co.ke", description: "Google's East Africa hub focusing on technology innovation and digital skills.", isVerified: true },
  { name: "Microsoft East Africa", logo: "MSF", industry: "Technology & IT", size: "50-200", website: "https://microsoft.com/africa", description: "Microsoft's regional office serving East African markets.", isVerified: true },
  { name: "Andela Kenya", logo: "AND", industry: "Technology & IT", size: "200-500", website: "https://andela.com", description: "A global talent network connecting skilled technologists with world-class companies.", isVerified: true },
  { name: "Twiga Foods", logo: "TWF", industry: "Agriculture & FMCG", size: "200-500", website: "https://twigafoods.com", description: "A technology-enabled fresh produce supply chain platform in Kenya.", isVerified: true },
  { name: "M-PESA (Safaricom)", logo: "MPS", industry: "Fintech", size: "500-1000", website: "https://mpesa.ke", description: "Africa's leading mobile money service transforming financial inclusion.", isVerified: true },
  { name: "Lipa Later", logo: "LPL", industry: "Fintech", size: "50-200", website: "https://lipalater.com", description: "A leading Buy Now Pay Later platform in East Africa.", isVerified: true },
  { name: "Absa Bank Kenya", logo: "ABS", industry: "Banking & Finance", size: "1000-5000", website: "https://absa.co.ke", description: "A major financial services provider in Kenya and across Africa.", isVerified: true },
  { name: "Deloitte East Africa", logo: "DEL", industry: "Consulting & Professional Services", size: "500-1000", website: "https://deloitte.com/ke", description: "A global professional services firm providing audit, consulting, and advisory services.", isVerified: true },
  { name: "PwC Kenya", logo: "PWC", industry: "Consulting & Professional Services", size: "500-1000", website: "https://pwc.co.ke", description: "One of the Big Four professional services firms operating in Kenya.", isVerified: true },
  { name: "Tsavo National Park (KWS)", logo: "KWS", industry: "Tourism & Hospitality", size: "500-1000", website: "https://kws.go.ke", description: "Kenya Wildlife Service managing national parks and conservation efforts.", isVerified: true },
  { name: "Sarova Hotels", logo: "SRV", industry: "Tourism & Hospitality", size: "500-1000", website: "https://sarovahotels.com", description: "A premier hospitality group with hotels, lodges, and resorts across Kenya.", isVerified: true },
  { name: "Britam Holdings", logo: "BRT", industry: "Insurance", size: "500-1000", website: "https://britam.com", description: "A leading diversified financial services group in East Africa.", isVerified: true },
  { name: "Jubilee Insurance", logo: "JUB", industry: "Insurance", size: "500-1000", website: "https://jubileeinsurance.com", description: "Kenya's first and largest insurance company with operations across East Africa.", isVerified: true },
  { name: "KenGen", logo: "KGN", industry: "Energy & Utilities", size: "1000-5000", website: "https://kengen.co.ke", description: "Kenya's leading electric power generating company.", isVerified: true },
  { name: "Kenya Power", logo: "KPC", industry: "Energy & Utilities", size: "5000+", website: "https://kplc.co.ke", description: "Kenya's sole electricity transmission and distribution company.", isVerified: true },
];

const categories = [
  { name: "Accounting & Finance", slug: "accounting-finance", icon: "Calculator", color: "#0D9488", description: "Jobs in accounting, auditing, banking, financial analysis, and taxation" },
  { name: "Administration & Office", slug: "admin-office", icon: "ClipboardList", color: "#6366F1", description: "Administrative, secretarial, and office management positions" },
  { name: "Agriculture & Agribusiness", slug: "agriculture", icon: "Sprout", color: "#16A34A", description: "Jobs in farming, agricultural research, food processing, and agribusiness" },
  { name: "Aviation & Travel", slug: "aviation", icon: "Plane", color: "#0891B2", description: "Pilot, cabin crew, travel agent, and aviation management roles" },
  { name: "Banking & Microfinance", slug: "banking", icon: "Landmark", color: "#7C3AED", description: "Banking operations, microfinance, credit management, and financial services" },
  { name: "Consulting & Professional Services", slug: "consulting", icon: "Briefcase", color: "#DC2626", description: "Management consulting, legal, audit, and professional advisory roles" },
  { name: "Customer Service & Support", slug: "customer-service", icon: "Headphones", color: "#2563EB", description: "Customer service, call center, helpdesk, and client support positions" },
  { name: "Education & Teaching", slug: "education", icon: "GraduationCap", color: "#CA8A04", description: "Teaching, lecturing, academic research, and education administration" },
  { name: "Energy & Utilities", slug: "energy", icon: "Zap", color: "#F59E0B", description: "Power generation, renewable energy, oil & gas, and utility management" },
  { name: "Engineering & Construction", slug: "engineering", icon: "HardHat", color: "#EA580C", description: "Civil, electrical, mechanical engineering and construction management" },
  { name: "Fintech & Digital Payments", slug: "fintech", icon: "Smartphone", color: "#8B5CF6", description: "Mobile money, digital banking, blockchain, and fintech innovation roles" },
  { name: "Government & Public Sector", slug: "government", icon: "Building", color: "#1D4ED8", description: "National and county government jobs, parastatals, and public service" },
  { name: "Healthcare & Medical", slug: "healthcare", icon: "Heart", color: "#EF4444", description: "Doctors, nurses, pharmacists, medical research, and healthcare administration" },
  { name: "HR & Recruitment", slug: "hr-recruitment", icon: "Users", color: "#D946EF", description: "Human resources management, talent acquisition, and organizational development" },
  { name: "Insurance", slug: "insurance", icon: "Shield", color: "#0284C7", description: "Underwriting, claims management, actuarial, and insurance sales roles" },
  { name: "Internships & Graduate Programs", slug: "internships", icon: "Rocket", color: "#059669", description: "Entry-level positions, internships, and management trainee programs" },
  { name: "IT & Software Development", slug: "it-software", icon: "Code", color: "#6D28D9", description: "Software engineering, data science, cloud computing, and IT support" },
  { name: "Legal & Compliance", slug: "legal", icon: "Scale", color: "#334155", description: "Legal counsel, compliance officers, company secretaries, and advocates" },
  { name: "Logistics & Supply Chain", slug: "logistics", icon: "Truck", color: "#78350F", description: "Procurement, warehousing, fleet management, and supply chain operations" },
  { name: "Marketing & Communications", slug: "marketing", icon: "Megaphone", color: "#E11D48", description: "Digital marketing, PR, content creation, brand management, and social media" },
  { name: "NGO & Development", slug: "ngo", icon: "Globe", color: "#15803D", description: "Non-governmental organizations, UN agencies, and development sector jobs" },
  { name: "Project Management", slug: "project-management", icon: "GanttChart", color: "#0F766E", description: "Project planning, coordination, monitoring and evaluation roles" },
  { name: "Remote & Work From Home", slug: "remote", icon: "Wifi", color: "#4F46E5", description: "Fully remote and hybrid work opportunities across all industries" },
  { name: "Sales & Business Development", slug: "sales", icon: "TrendingUp", color: "#B91C1C", description: "Sales executives, account managers, business development, and partnerships" },
  { name: "Scholarships & Grants", slug: "scholarships", icon: "Award", color: "#9333EA", description: "Funding opportunities, fellowships, and educational grants" },
  { name: "Tourism & Hospitality", slug: "tourism", icon: "MapPin", color: "#0891B2", description: "Hotel management, tour operations, event planning, and restaurant management" },
];

const jobs = [
  { title: "Senior Software Engineer", company: "Safaricom PLC", employerIdx: 0, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 250000, salaryMax: 400000, isFeatured: true, description: "Join Safaricom's digital transformation team to build next-generation mobile and web applications serving over 40 million customers. You will lead the design and development of scalable microservices architectures and mentor junior developers.", requirements: "Bachelor's degree in Computer Science or related field. 5+ years experience in Java, Python, or Node.js. Experience with cloud platforms (AWS/Azure/GCP). Strong understanding of microservices architecture and RESTful APIs.", howToApply: "Apply online through the Safaricom careers portal. Include your CV, cover letter, and portfolio of projects.", closingDate: "2026-05-15", isRemote: false },
  { title: "Data Scientist", company: "Equity Bank Kenya", employerIdx: 1, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 200000, salaryMax: 350000, isFeatured: true, description: "Leverage advanced analytics and machine learning to drive data-informed decision making across the bank's operations, risk management, and customer experience teams. Work with petabytes of financial data.", requirements: "Master's degree in Statistics, Data Science, or related field. 3+ years experience in data science. Proficiency in Python, R, SQL, and ML frameworks. Experience with financial data analytics preferred.", howToApply: "Submit your application through the Equity Bank careers portal. Include a portfolio of data science projects.", closingDate: "2026-05-20", isRemote: false },
  { title: "Marketing Manager", company: "East Africa Breweries Limited", employerIdx: 5, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Marketing & Communications", salaryMin: 180000, salaryMax: 300000, isFeatured: true, description: "Lead marketing strategy and brand activation campaigns for EABL's premium product portfolio. Manage a team of 15 marketing professionals and oversee a KSh 500M annual marketing budget.", requirements: "MBA with marketing specialization. 7+ years in brand marketing, FMCG preferred. Proven track record of successful marketing campaigns. Strong leadership and team management skills.", howToApply: "Apply through the EABL careers page on Diageo's website. Submit CV, cover letter, and portfolio of marketing campaigns.", closingDate: "2026-05-10", isRemote: false },
  { title: "Registered Nurse - ICU", company: "Aga Khan University Hospital", employerIdx: 12, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Healthcare & Medical", salaryMin: 80000, salaryMax: 150000, description: "Provide specialized critical care nursing in the hospital's Intensive Care Unit. Monitor patients, administer medications, and collaborate with the multidisciplinary healthcare team.", requirements: "Bachelor of Science in Nursing. Valid NCK license. 3+ years ICU nursing experience. BLS/ACLS certification required.", howToApply: "Submit applications through the Aga Khan University Hospital careers portal. Include copies of your nursing license and certifications.", closingDate: "2026-05-25", isRemote: false },
  { title: "Financial Analyst", company: "Deloitte East Africa", employerIdx: 22, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Accounting & Finance", salaryMin: 120000, salaryMax: 200000, description: "Provide financial advisory services to clients across East Africa. Conduct financial modeling, due diligence, and market analysis for mergers, acquisitions, and capital raising transactions.", requirements: "CPA(K) or ACCA qualification. Bachelor's degree in Finance or Accounting. 2-4 years experience in financial analysis. Strong Excel and financial modeling skills.", howToApply: "Apply through Deloitte's global careers portal. Select East Africa region and Financial Advisory practice.", closingDate: "2026-06-01", isRemote: false },
  { title: "Civil Engineer - Roads", company: "Kenya National Highways Authority", employerIdx: 13, location: "Nakuru", county: "Nakuru", type: "Full-Time", category: "Engineering & Construction", salaryMin: 100000, salaryMax: 180000, description: "Oversee the design, construction, and maintenance of national highways in the Rift Valley region. Manage contractor relationships and ensure quality standards compliance.", requirements: "Bachelor's degree in Civil Engineering. Registered with EBK. 5+ years experience in road construction projects. Knowledge of Kenyan road design standards.", howToApply: "Submit applications through the Public Service Commission portal. Include copies of professional registration and academic certificates.", closingDate: "2026-05-30", isRemote: false },
  { title: "Product Manager - M-PESA", company: "M-PESA (Safaricom)", employerIdx: 19, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Fintech & Digital Payments", salaryMin: 250000, salaryMax: 400000, isFeatured: true, description: "Lead product strategy for new M-PESA features and services. Own the product roadmap from conception to launch, working with engineering, design, and business teams.", requirements: "MBA or Bachelor's degree in Computer Science/Business. 5+ years product management experience. Mobile fintech experience highly preferred. Data-driven decision making skills.", howToApply: "Apply through the Safaricom careers portal. Include a product portfolio demonstrating your impact on user growth and engagement.", closingDate: "2026-05-18", isRemote: true },
  { title: "Secondary School Teacher - Mathematics", company: "Ministry of Education", employerIdx: 13, location: "Mombasa", county: "Mombasa", type: "Full-Time", category: "Education & Teaching", salaryMin: 40000, salaryMax: 70000, description: "Teach mathematics to secondary school students (Form 1-4) in a national school. Develop lesson plans, assess student progress, and participate in co-curricular activities.", requirements: "Bachelor of Education (Mathematics). Registered with TSC. 2+ years teaching experience. Knowledge of CBC curriculum.", howToApply: "Apply through the Teachers Service Commission (TSC) online portal. Submit academic and professional certificates.", closingDate: "2026-06-15", isRemote: false },
  { title: "Human Resources Business Partner", company: "KCB Group", employerIdx: 2, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "HR & Recruitment", salaryMin: 150000, salaryMax: 250000, description: "Partner with business leaders to develop and implement HR strategies that support organizational objectives. Manage talent acquisition, performance management, and employee engagement initiatives.", requirements: "Bachelor's degree in HR Management or related field. CHRP certification. 5+ years HRBP experience. Knowledge of Kenyan labor laws.", howToApply: "Apply through the KCB Group careers page. Submit your CV and cover letter addressed to the HR Director.", closingDate: "2026-05-22", isRemote: false },
  { title: "NGO Program Manager - Health", company: "World Vision Kenya", employerIdx: 9, location: "Kisumu", county: "Kisumu", type: "Contract", category: "NGO & Development", salaryMin: 180000, salaryMax: 280000, description: "Manage health and nutrition programs in the Lake Victoria region. Oversee program implementation, budget management, stakeholder engagement, and impact reporting.", requirements: "Master's degree in Public Health or related field. 7+ years NGO program management experience. Experience with USAID-funded programs. Strong proposal writing skills.", howToApply: "Apply through the World Vision International career portal. Select Kenya location and Program Management category.", closingDate: "2026-05-28", isRemote: false },
  { title: "UX/UI Designer", company: "Andela Kenya", employerIdx: 17, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 150000, salaryMax: 280000, isFeatured: true, description: "Design intuitive and beautiful user interfaces for Andela's platform and client products. Conduct user research, create wireframes and prototypes, and collaborate with engineering teams.", requirements: "Portfolio demonstrating UX/UI design skills. 3+ years experience. Proficiency in Figma and design systems. Understanding of accessibility standards.", howToApply: "Apply through Andela's careers page. Submit your portfolio along with your application.", closingDate: "2026-05-12", isRemote: true },
  { title: "Supply Chain Manager", company: "Bidco Africa", employerIdx: 6, location: "Thika", county: "Kiambu", type: "Full-Time", category: "Logistics & Supply Chain", salaryMin: 150000, salaryMax: 250000, description: "Manage end-to-end supply chain operations for Bidco's edible oils division. Oversee procurement, warehousing, distribution, and logistics across East Africa.", requirements: "Bachelor's degree in Supply Chain Management. CIPS or KISM certification. 5+ years supply chain experience in FMCG. ERP system proficiency (SAP preferred).", howToApply: "Apply through the Bidco Africa careers portal or send your CV to careers@bidcoafrica.com.", closingDate: "2026-06-05", isRemote: false },
  { title: "Pilot - First Officer", company: "Kenya Airways", employerIdx: 4, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Aviation & Travel", salaryMin: 300000, salaryMax: 500000, description: "Fly as First Officer on Kenya Airways' domestic and regional routes. Ensure safe and efficient flight operations while delivering exceptional passenger experience.", requirements: "Valid Commercial Pilot License (CPL) with multi-engine rating. 500+ total flight hours. Class 1 Medical Certificate. ICAO English Level 4 or above.", howToApply: "Apply through the Kenya Airways careers portal. Submit copies of all licenses and medical certificates.", closingDate: "2026-06-10", isRemote: false },
  { title: "Sales Executive - Corporate Banking", company: "NCBA Group", employerIdx: 3, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Sales & Business Development", salaryMin: 100000, salaryMax: 250000, description: "Drive corporate banking revenue by acquiring and managing relationships with medium and large enterprises. Meet and exceed quarterly sales targets.", requirements: "Bachelor's degree in Business or Finance. 3+ years corporate banking sales experience. Strong networking and relationship management skills. Knowledge of corporate banking products.", howToApply: "Apply through the NCBA Group careers page. Include your CV and a cover letter.", closingDate: "2026-05-20", isRemote: false },
  { title: "Legal Counsel - Corporate", company: "PwC Kenya", employerIdx: 23, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Legal & Compliance", salaryMin: 180000, salaryMax: 350000, description: "Provide legal advisory services on corporate transactions, mergers and acquisitions, regulatory compliance, and governance matters for PwC's clients across East Africa.", requirements: "LLB degree, Advocate of the High Court of Kenya. 5+ years corporate law experience. Strong knowledge of Kenyan company law and regulatory frameworks.", howToApply: "Apply through the PwC global careers portal. Select Kenya and Legal/Tax practice area.", closingDate: "2026-05-30", isRemote: false },
  { title: "Mechanical Engineer - Maintenance", company: "KenGen", employerIdx: 28, location: "Nakuru", county: "Nakuru", type: "Full-Time", category: "Engineering & Construction", salaryMin: 120000, salaryMax: 200000, description: "Lead maintenance planning and execution for geothermal power generation equipment. Ensure optimal plant availability and reliability.", requirements: "Bachelor's degree in Mechanical Engineering. Registered with EBK. 4+ years experience in power plant maintenance. Knowledge of condition monitoring and predictive maintenance.", howToApply: "Submit applications through the KenGen careers portal. Include copies of professional registration.", closingDate: "2026-06-08", isRemote: false },
  { title: "Digital Marketing Specialist", company: "Sarova Hotels", employerIdx: 25, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Marketing & Communications", salaryMin: 80000, salaryMax: 150000, description: "Develop and execute digital marketing strategies across social media, email, SEO, and paid advertising channels to drive hotel bookings and brand awareness.", requirements: "Bachelor's degree in Marketing or Communications. 3+ years digital marketing experience. Google Analytics and Ads certifications. Experience in hospitality marketing preferred.", howToApply: "Send your CV and portfolio to careers@sarovahotels.com with subject line 'Digital Marketing Specialist Application'.", closingDate: "2026-05-15", isRemote: true },
  { title: "Research Scientist - Epidemiology", company: "Kenya Medical Research Institute", employerIdx: 11, location: "Kisumu", county: "Kisumu", type: "Contract", category: "Healthcare & Medical", salaryMin: 150000, salaryMax: 250000, description: "Lead epidemiological research studies on infectious diseases in Western Kenya. Design research protocols, conduct field studies, and publish findings in peer-reviewed journals.", requirements: "PhD in Epidemiology or related field. 3+ years post-doctoral research experience. Strong publication record. Experience with infectious disease research.", howToApply: "Apply through the KEMRI careers portal. Submit your CV, research statement, and list of publications.", closingDate: "2026-06-20", isRemote: false },
  { title: "Accountant - Tax", company: "Kenya Revenue Authority", employerIdx: 14, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Government & Public Sector", salaryMin: 60000, salaryMax: 120000, description: "Handle tax assessment, collection, and compliance for corporate taxpayers. Conduct tax audits and ensure adherence to Kenya's tax laws and regulations.", requirements: "Bachelor's degree in Accounting or Finance. CPA(K) qualification. 2+ years experience in tax accounting. Knowledge of Kenyan tax laws and iTax system.", howToApply: "Apply through the KRA careers portal or Public Service Commission website.", closingDate: "2026-05-25", isRemote: false },
  { title: "Procurement Officer", company: "UNICEF Kenya", employerIdx: 10, location: "Nairobi", county: "Nairobi", type: "Fixed-Term", category: "NGO & Development", salaryMin: 200000, salaryMax: 320000, description: "Manage procurement processes for UNICEF Kenya's program supplies and services. Ensure compliance with UN procurement policies and achieve best value for money.", requirements: "Master's degree in Procurement, Supply Chain, or Business. CIPS certification preferred. 5+ years procurement experience. UN or international organization experience preferred.", howToApply: "Apply through the UNICEF careers portal (careers.unicef.org). Select Kenya duty station.", closingDate: "2026-06-01", isRemote: false },
  { title: "Frontend Developer (React)", company: "Twiga Foods", employerIdx: 18, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 120000, salaryMax: 220000, isFeatured: true, description: "Build modern, responsive web interfaces for Twiga's supply chain platform serving thousands of farmers and vendors across Kenya. Work with React, TypeScript, and modern web technologies.", requirements: "3+ years experience with React/TypeScript. Proficiency in modern CSS (Tailwind). Experience with state management (Redux/Zustand). Understanding of REST APIs and GraphQL.", howToApply: "Apply through Twiga Foods careers page or send your CV and GitHub portfolio to jobs@twigafoods.com.", closingDate: "2026-05-16", isRemote: true },
  { title: "Insurance Claims Manager", company: "Jubilee Insurance", employerIdx: 27, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Insurance", salaryMin: 150000, salaryMax: 250000, description: "Manage the claims department, oversee claims processing, and ensure timely settlement of insurance claims. Lead a team of claims assessors and investigators.", requirements: "Bachelor's degree in Insurance or related field. ACII or AIIK qualification. 7+ years claims management experience. Strong analytical and decision-making skills.", howToApply: "Apply through the Jubilee Insurance careers portal. Submit CV and cover letter.", closingDate: "2026-05-30", isRemote: false },
  { title: "Agricultural Extension Officer", company: "Ministry of Agriculture", employerIdx: 13, location: "Eldoret", county: "Uasin Gishu", type: "Full-Time", category: "Agriculture & Agribusiness", salaryMin: 45000, salaryMax: 75000, description: "Provide agricultural extension services to farmers in the North Rift region. Train farmers on modern farming techniques, market access, and value addition.", requirements: "Bachelor's degree in Agricultural Extension or Agronomy. 2+ years experience in agricultural extension. Knowledge of agricultural value chains.", howToApply: "Apply through the Public Service Commission portal. Submit academic and professional certificates.", closingDate: "2026-06-15", isRemote: false },
  { title: "Customer Experience Lead", company: "Lipa Later", employerIdx: 20, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Customer Service & Support", salaryMin: 100000, salaryMax: 180000, description: "Lead the customer experience team to deliver exceptional service to Lipa Later's growing customer base. Develop CX strategies, manage the support team, and drive customer satisfaction.", requirements: "Bachelor's degree in Business or related field. 4+ years customer experience management experience. Knowledge of CRM systems. Strong leadership skills.", howToApply: "Apply through the Lipa Later careers page. Submit your CV and a brief cover letter.", closingDate: "2026-05-22", isRemote: true },
  { title: "Project Manager - Renewable Energy", company: "Kenya Power", employerIdx: 29, location: "Nairobi", county: "Nairobi", type: "Contract", category: "Project Management", salaryMin: 200000, salaryMax: 350000, description: "Manage renewable energy integration projects including solar and wind power connections to the national grid. Oversee project timelines, budgets, and stakeholder management.", requirements: "Bachelor's degree in Electrical Engineering. PMP certification. 7+ years project management experience. Experience in renewable energy projects.", howToApply: "Apply through the Kenya Power careers portal. Submit CV, PMP certification, and project portfolio.", closingDate: "2026-06-12", isRemote: false },
  { title: "Tour Guide - National Parks", company: "Tsavo National Park (KWS)", employerIdx: 24, location: "Voi", county: "Taita Taveta", type: "Full-Time", category: "Tourism & Hospitality", salaryMin: 35000, salaryMax: 60000, description: "Lead guided tours and educational programs in Tsavo East and West National Parks. Share knowledge about wildlife, conservation, and ecosystem management with visitors.", requirements: "Diploma in Tourism or Wildlife Management. Silver or Gold level guiding certification from KATO. 2+ years experience as a tour guide. First aid certification.", howToApply: "Submit applications to the KWS regional office in Voi or through the KWS careers portal.", closingDate: "2026-06-01", isRemote: false },
  { title: "Graduate Management Trainee", company: "Absa Bank Kenya", employerIdx: 21, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Internships & Graduate Programs", salaryMin: 70000, salaryMax: 100000, isUrgent: true, description: "Join Absa's prestigious 18-month management trainee program. Rotate through various departments including Retail Banking, Corporate Banking, Risk, and Operations.", requirements: "Bachelor's degree with Second Class Upper or GPA 3.0+. Graduated in 2024 or 2025. Strong leadership and communication skills. No prior work experience required.", howToApply: "Apply through the Absa Group careers portal. Select 'Graduate Programme' and Kenya location. Application deadline is strict.", closingDate: "2026-05-08", isRemote: false },
  { title: "Backend Developer (Python)", company: "Microsoft East Africa", employerIdx: 16, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 280000, salaryMax: 450000, isFeatured: true, description: "Build scalable backend services and APIs for Microsoft's Africa-focused products. Work with Python, Azure cloud services, and cutting-edge AI technologies.", requirements: "Bachelor's in Computer Science or equivalent. 5+ years Python development experience. Experience with Azure/AWS cloud services. Knowledge of microservices and containerization (Docker/K8s).", howToApply: "Apply through the Microsoft careers portal. Select Africa region and Backend Engineering roles.", closingDate: "2026-05-30", isRemote: true },
  { title: "Monitoring & Evaluation Specialist", company: "Safaricom Foundation", employerIdx: 8, location: "Nairobi", county: "Nairobi", type: "Contract", category: "NGO & Development", salaryMin: 120000, salaryMax: 200000, description: "Design and implement M&E frameworks for Safaricom Foundation's education, health, and environmental programs. Conduct impact assessments and data-driven reporting.", requirements: "Master's degree in Monitoring & Evaluation, Statistics, or related field. 5+ years M&E experience in development sector. Strong quantitative and qualitative research skills.", howToApply: "Apply through the Safaricom Foundation website. Submit CV, cover letter, and sample M&E framework.", closingDate: "2026-05-28", isRemote: false },
  { title: "Internal Auditor", company: "Britam Holdings", employerIdx: 26, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Accounting & Finance", salaryMin: 120000, salaryMax: 200000, description: "Conduct internal audits across Britam's insurance, asset management, and banking operations. Identify risks, assess controls, and recommend improvements.", requirements: "Bachelor's degree in Accounting or Finance. CPA(K) and CIA certification. 3+ years internal audit experience. Knowledge of insurance industry regulations.", howToApply: "Apply through the Britam careers portal. Submit CV and cover letter.", closingDate: "2026-06-05", isRemote: false },
  { title: "Electrical Engineer - Solar", company: "KenGen", employerIdx: 28, location: "Garissa", county: "Garissa", type: "Contract", category: "Engineering & Construction", salaryMin: 130000, salaryMax: 220000, description: "Lead the design and implementation of solar power projects in Kenya's arid and semi-arid regions. Manage project execution from feasibility studies to commissioning.", requirements: "Bachelor's degree in Electrical Engineering. EBK registration. 4+ years experience in solar/renewable energy projects. Knowledge of grid connection standards.", howToApply: "Apply through the KenGen careers portal.", closingDate: "2026-06-15", isRemote: false },
  { title: "Brand Manager", company: "Unilever Kenya", employerIdx: 7, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Marketing & Communications", salaryMin: 180000, salaryMax: 300000, description: "Manage brand strategy and P&L for one of Unilever's key brands in the Kenyan market. Drive brand equity, market share growth, and innovation pipeline.", requirements: "MBA with marketing specialization. 5+ years brand management experience in FMCG. Strong analytical and strategic thinking skills. Experience with consumer insights research.", howToApply: "Apply through the Unilever careers portal. Select Kenya and Marketing function.", closingDate: "2026-05-20", isRemote: false },
  { title: "Business Intelligence Analyst", company: "Google Kenya", employerIdx: 15, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 200000, salaryMax: 350000, isFeatured: true, description: "Transform data into actionable business insights for Google's East Africa operations. Build dashboards, conduct ad-hoc analysis, and support strategic decision making.", requirements: "Bachelor's degree in Statistics, Mathematics, or Computer Science. 3+ years BI experience. Advanced SQL and Python skills. Experience with data visualization tools (Looker/Tableau).", howToApply: "Apply through the Google careers portal. Select Kenya location and Data/Analytics roles.", closingDate: "2026-06-01", isRemote: true },
  { title: "Network Administrator", company: "Kenya Airways", employerIdx: 4, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 100000, salaryMax: 180000, description: "Manage and maintain Kenya Airways' enterprise network infrastructure including LAN, WAN, WiFi, and security systems across all airport locations.", requirements: "Bachelor's degree in IT or related field. CCNA/CCNP certification. 3+ years network administration experience. Knowledge of aviation IT systems preferred.", howToApply: "Apply through the Kenya Airways careers portal.", closingDate: "2026-06-10", isRemote: false },
  { title: "Restaurant Manager", company: "Sarova Hotels", employerIdx: 25, location: "Mombasa", county: "Mombasa", type: "Full-Time", category: "Tourism & Hospitality", salaryMin: 60000, salaryMax: 100000, description: "Manage daily restaurant operations at a beach resort property. Oversee food quality, customer service, staff scheduling, and inventory management.", requirements: "Diploma or degree in Hospitality Management. 4+ years restaurant management experience. Food safety certification. Strong customer service orientation.", howToApply: "Send your CV to careers@sarovahotels.com with subject line 'Restaurant Manager - Mombasa'.", closingDate: "2026-05-25", isRemote: false },
  { title: "Underwriting Manager", company: "Britam Holdings", employerIdx: 26, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Insurance", salaryMin: 180000, salaryMax: 300000, description: "Lead the underwriting team for life and general insurance products. Develop underwriting policies, assess risk, and ensure portfolio profitability.", requirements: "Bachelor's degree in Insurance, Actuarial Science, or related field. AIIK or ACII qualification. 7+ years underwriting experience. Strong analytical and leadership skills.", howToApply: "Apply through the Britam careers portal.", closingDate: "2026-06-08", isRemote: false },
  { title: "Content Writer", company: "Safaricom PLC", employerIdx: 0, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Marketing & Communications", salaryMin: 70000, salaryMax: 120000, description: "Create engaging content for Safaricom's digital channels including website, social media, blog, and customer communications. Develop content strategy aligned with brand guidelines.", requirements: "Bachelor's degree in Communications, Journalism, or related field. 2+ years professional content writing experience. Strong portfolio of published work. SEO knowledge preferred.", howToApply: "Apply through the Safaricom careers portal. Include a portfolio of writing samples.", closingDate: "2026-05-20", isRemote: true },
  { title: "Environmental Scientist", company: "Tsavo National Park (KWS)", employerIdx: 24, location: "Voi", county: "Taita Taveta", type: "Contract", category: "Agriculture & Agribusiness", salaryMin: 80000, salaryMax: 140000, description: "Conduct environmental impact assessments and biodiversity monitoring in Tsavo ecosystem. Develop conservation strategies and manage environmental research programs.", requirements: "Master's degree in Environmental Science or related field. 3+ years experience in environmental research. Knowledge of Kenyan environmental regulations.", howToApply: "Submit applications to the KWS careers portal or regional office.", closingDate: "2026-06-10", isRemote: false },
  { title: "Admin Assistant", company: "Deloitte East Africa", employerIdx: 22, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Administration & Office", salaryMin: 40000, salaryMax: 65000, description: "Provide comprehensive administrative support to the consulting team. Manage schedules, correspondence, travel arrangements, and office operations.", requirements: "Diploma in Business Administration or related field. 2+ years administrative experience. Proficiency in MS Office suite. Strong organizational skills.", howToApply: "Apply through the Deloitte careers portal. Select East Africa region.", closingDate: "2026-05-30", isRemote: false },
  { title: "DevOps Engineer", company: "Andela Kenya", employerIdx: 17, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 200000, salaryMax: 350000, description: "Build and maintain CI/CD pipelines, cloud infrastructure, and monitoring systems. Ensure high availability and performance of production systems.", requirements: "3+ years DevOps experience. Proficiency with AWS/Azure/GCP. Experience with Docker, Kubernetes, Terraform. Strong scripting skills (Python/Bash).", howToApply: "Apply through Andela's careers page.", closingDate: "2026-05-25", isRemote: true },
  { title: "Compliance Officer - Banking", company: "NCBA Group", employerIdx: 3, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Legal & Compliance", salaryMin: 120000, salaryMax: 200000, description: "Ensure compliance with CBK regulations, AML/CFT requirements, and internal policies. Conduct compliance reviews, risk assessments, and staff training.", requirements: "Bachelor's degree in Law, Finance, or related field. 4+ years compliance experience in banking. Knowledge of CBK guidelines and AML regulations.", howToApply: "Apply through the NCBA Group careers page.", closingDate: "2026-06-01", isRemote: false },
  { title: "Quantity Surveyor", company: "Kenya National Highways Authority", employerIdx: 13, location: "Mombasa", county: "Mombasa", type: "Contract", category: "Engineering & Construction", salaryMin: 100000, salaryMax: 180000, description: "Manage cost estimation, measurement, and contract administration for road construction projects in the Coast region.", requirements: "Bachelor's degree in Quantity Surveying. Registered with IQSK/EBK. 4+ years experience in infrastructure projects. Knowledge of FIDIC contracts.", howToApply: "Apply through the Public Service Commission portal.", closingDate: "2026-06-15", isRemote: false },
  { title: "Graphic Designer", company: "Bidco Africa", employerIdx: 6, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Marketing & Communications", salaryMin: 50000, salaryMax: 90000, description: "Create visual designs for product packaging, advertising campaigns, and digital marketing materials. Maintain brand consistency across all touchpoints.", requirements: "Diploma or degree in Graphic Design. 2+ years professional design experience. Proficiency in Adobe Creative Suite. Strong portfolio.", howToApply: "Apply through the Bidco Africa careers portal or send your portfolio to careers@bidcoafrica.com.", closingDate: "2026-05-22", isRemote: true },
  { title: "Clinical Pharmacist", company: "Aga Khan University Hospital", employerIdx: 12, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Healthcare & Medical", salaryMin: 100000, salaryMax: 180000, description: "Provide clinical pharmacy services including drug therapy management, patient counseling, and medication safety oversight. Collaborate with medical teams.", requirements: "Bachelor of Pharmacy degree. Registered with PPB. 3+ years clinical pharmacy experience. Knowledge of drug information systems.", howToApply: "Apply through the Aga Khan University Hospital careers portal.", closingDate: "2026-06-05", isRemote: false },
  { title: "Data Engineer", company: "Equity Bank Kenya", employerIdx: 1, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 180000, salaryMax: 300000, description: "Build and optimize data pipelines and infrastructure for Equity Bank's data platform. Design data models, implement ETL processes, and support analytics teams.", requirements: "Bachelor's in Computer Science or related field. 3+ years data engineering experience. Proficiency in SQL, Python, Spark, and cloud data services. Experience with financial data preferred.", howToApply: "Apply through the Equity Bank careers portal.", closingDate: "2026-06-10", isRemote: false },
  { title: "Program Officer - Education", company: "World Vision Kenya", employerIdx: 9, location: "Narok", county: "Narok", type: "Contract", category: "NGO & Development", salaryMin: 90000, salaryMax: 150000, description: "Implement education programs in Narok County focusing on improving access to quality education for children in pastoral communities.", requirements: "Bachelor's degree in Education or Social Sciences. 3+ years experience in education programming. Experience working with pastoral communities preferred.", howToApply: "Apply through the World Vision International career portal.", closingDate: "2026-06-08", isRemote: false },
  { title: "Credit Analyst", company: "KCB Group", employerIdx: 2, location: "Kisumu", county: "Kisumu", type: "Full-Time", category: "Banking & Microfinance", salaryMin: 80000, salaryMax: 150000, description: "Evaluate creditworthiness of loan applicants, conduct financial analysis, and make credit recommendations. Manage credit risk within the bank's portfolio.", requirements: "Bachelor's degree in Finance or Accounting. CPA(K) or ACCA qualification. 2+ years credit analysis experience. Strong financial modeling skills.", howToApply: "Apply through the KCB Group careers page.", closingDate: "2026-05-30", isRemote: false },
  { title: "Security Operations Center Analyst", company: "Safaricom PLC", employerIdx: 0, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "IT & Software Development", salaryMin: 120000, salaryMax: 200000, description: "Monitor and respond to cybersecurity threats targeting Safaricom's infrastructure. Conduct incident analysis and implement security measures.", requirements: "Bachelor's in IT/Computer Science. CISSP, CEH, or equivalent certification. 3+ years SOC experience. Knowledge of SIEM tools and threat intelligence.", howToApply: "Apply through the Safaricom careers portal.", closingDate: "2026-06-15", isRemote: false },
  { title: "Hotel General Manager", company: "Sarova Hotels", employerIdx: 25, location: "Nairobi", county: "Nairobi", type: "Full-Time", category: "Tourism & Hospitality", salaryMin: 200000, salaryMax: 400000, description: "Oversee all hotel operations including rooms, F&B, events, and maintenance. Drive revenue growth, guest satisfaction, and team development.", requirements: "Degree in Hospitality Management. 10+ years hotel operations experience with 5+ years in GM role. Strong financial acumen and leadership skills.", howToApply: "Send your CV to the Group HR Director at careers@sarovahotels.com.", closingDate: "2026-06-20", isRemote: false },
  { title: "Quantity Surveyor Intern", company: "Ministry of Transport", employerIdx: 13, location: "Nairobi", county: "Nairobi", type: "Internship", category: "Internships & Graduate Programs", salaryMin: 25000, salaryMax: 35000, description: "Gain hands-on experience in quantity surveying for government infrastructure projects. Assist senior surveyors with cost estimation and contract management.", requirements: "Diploma or Degree in Quantity Surveying. Currently enrolled or recent graduate. Basic knowledge of construction measurement. Proficiency in MS Excel.", howToApply: "Apply through the Public Service Commission internship portal.", closingDate: "2026-06-30", isRemote: false },
];

const scholarships = [
  { title: "MasterCard Foundation Scholars Program at University of Nairobi", provider: "MasterCard Foundation", description: "Full scholarship for economically disadvantaged but academically talented students from Kenya pursuing undergraduate or master's degrees at the University of Nairobi.", eligibility: "Kenyan citizens aged 18-29. Strong academic record. Demonstrated financial need. Leadership potential.", deadline: "2026-07-15", amount: "Full tuition + living allowance", level: "Undergraduate", isFeatured: true },
  { title: "DAAD Kenya Scholarships for Postgraduate Studies", provider: "German Academic Exchange Service (DAAD)", description: "Funding for Kenyan students to pursue Master's or PhD degrees at German universities. Covers tuition, travel, health insurance, and monthly stipend.", eligibility: "Kenyan citizens. Bachelor's degree for Master's, Master's for PhD. 2 years work experience for Master's applicants.", deadline: "2026-06-30", amount: "Full funding (up to EUR 934/month)", level: "Masters", isFeatured: true },
  { title: "Kenya Education Fund (KEF) Scholarships", provider: "Kenya Education Fund", description: "Provides scholarships for bright and needy Kenyan students to attend secondary school and university. Focus on students from marginalized communities.", eligibility: "Kenyan citizens from disadvantaged backgrounds. Strong academic performance. Admission to recognized institution.", deadline: "2026-08-01", amount: "KSh 50,000 - 200,000/year", level: "Undergraduate" },
  { title: "Google Africa Developer Scholarship", provider: "Google", description: "Free access to Google Career Certificates and Pluralsight courses in Android development, cloud computing, and data analytics for African developers.", eligibility: "African residents 18+. Basic programming knowledge. Commitment to complete the program.", deadline: "2026-05-30", amount: "Free certification", level: "Professional" },
  { title: "Aga Khan Foundation International Scholarship", provider: "Aga Khan Foundation", description: "50% grant and 50% loan for outstanding students from developing countries pursuing postgraduate studies at top universities worldwide.", eligibility: "Kenyan citizens under 30. Excellent academic record. Admission to reputable university. Demonstrated financial need.", deadline: "2026-09-01", amount: "50% grant + 50% loan (tuition + living costs)", level: "Masters", isFeatured: true },
  { title: "Equity Group Foundation Wings to Fly Scholarship", provider: "Equity Group Foundation", description: "Comprehensive scholarship for academically gifted but financially disadvantaged students to attend leading high schools and universities in Kenya.", eligibility: "KCPE/KCSE top performers from needy families. Strong leadership qualities. Community involvement.", deadline: "2026-07-15", amount: "Full tuition + mentorship + leadership development", level: "Undergraduate" },
  { title: "Fulbright Foreign Student Program - Kenya", provider: "US Department of State", description: "Full scholarships for Kenyan graduate students, young professionals, and artists to study, research, or teach in the United States for one academic year.", eligibility: "Kenyan citizens. Bachelor's degree with strong academic record. Proficiency in English. Leadership potential.", deadline: "2026-10-15", amount: "Full funding (tuition, travel, living allowance)", level: "Masters" },
  { title: "Microsoft AI School Africa Scholarship", provider: "Microsoft", description: "Free AI and machine learning training for African tech professionals. Includes access to Azure AI services and certification exam vouchers.", eligibility: "African residents. Background in software development or data science. Commitment to complete 6-month program.", deadline: "2026-06-15", amount: "Free training + certification", level: "Professional" },
];

const articles = [
  { title: "How to Write a Winning CV in Kenya: The Complete 2026 Guide", slug: "winning-cv-kenya-guide", excerpt: "Stand out from thousands of applicants with a professionally crafted CV tailored for the Kenyan job market. Learn the essential sections, formatting tips, and common mistakes to avoid.", content: "Your CV is your first impression with a potential employer. In Kenya's competitive job market, where a single position can attract hundreds of applications, your CV needs to be exceptional to get noticed. This comprehensive guide covers everything from choosing the right format to highlighting your achievements effectively.", category: "CV & Interview Tips" },
  { title: "Top 15 Highest Paying Jobs in Kenya for 2026", slug: "highest-paying-jobs-kenya-2026", excerpt: "Discover which careers command the highest salaries in Kenya, from tech roles to specialized medical positions. Updated salary data and industry trends for job seekers.", content: "Kenya's job market is evolving rapidly with technology driving salary growth across multiple sectors. Based on industry surveys and recruitment data, we've compiled the most comprehensive list of the highest-paying careers in Kenya for 2026.", category: "Salary & Career Growth" },
  { title: "How to Prepare for Safaricom Job Interviews", slug: "safaricom-interview-prep", excerpt: "Insider tips for acing interviews at Kenya's most sought-after employer. Learn about their interview process, common questions, and what they look for in candidates.", content: "Safaricom is consistently ranked as one of Kenya's best employers, but their hiring process is rigorous. With over 50,000 applications monthly for various positions, understanding their interview methodology can give you a significant advantage.", category: "Company Guides" },
  { title: "Government Job Application Guide: TSC, KRA & County Jobs", slug: "government-job-application-guide", excerpt: "Navigate the Kenyan government job application process with ease. Step-by-step instructions for TSC, KRA, county government, and public service commission applications.", content: "Government jobs in Kenya offer job security, good benefits, and career progression. However, the application process can be complex and competitive. This guide breaks down the process for various government bodies.", category: "Government Jobs" },
  { title: "The Rise of Remote Work in Kenya: Opportunities & Challenges", slug: "remote-work-kenya", excerpt: "Kenya's remote work sector is booming. Learn about available opportunities, required skills, and how to position yourself for location-independent careers.", content: "The COVID-19 pandemic accelerated remote work adoption globally, and Kenya has emerged as one of Africa's leading destinations for remote talent. With improving internet infrastructure and a growing tech ecosystem, opportunities continue to expand.", category: "Remote Work" },
  { title: "Scholarship Application Tips: How to Win Funding for Your Studies", slug: "scholarship-application-tips", excerpt: "Competition for scholarships in Kenya is intense. Learn proven strategies to strengthen your applications and increase your chances of securing educational funding.", content: "Thousands of scholarships are available to Kenyan students every year, but many go unclaimed because applicants don't know how to present themselves effectively. This article provides practical tips from successful scholarship recipients.", category: "Scholarships" },
];

async function seed() {
  console.log("Seeding database...");

  // Clear existing data
  await prisma.job.deleteMany();
  await prisma.employer.deleteMany();
  await prisma.category.deleteMany();
  await prisma.article.deleteMany();
  await prisma.scholarship.deleteMany();
  await prisma.subscriber.deleteMany();

  // Create employers
  console.log("Creating employers...");
  const createdEmployers = [];
  for (const emp of employers) {
    const created = await prisma.employer.create({
      data: emp,
    });
    createdEmployers.push(created);
  }

  // Create categories
  console.log("Creating categories...");
  for (const cat of categories) {
    await prisma.category.create({ data: cat });
  }

  // Create jobs
  console.log("Creating jobs...");
  for (const job of jobs) {
    const employer = createdEmployers[job.employerIdx];
    if (!employer) continue;
    
    await prisma.job.create({
      data: {
        title: job.title,
        company: job.company,
        logo: job.company.substring(0, 2).toUpperCase(),
        location: job.location,
        county: job.county,
        type: job.type,
        category: job.category,
        salaryMin: job.salaryMin,
        salaryMax: job.salaryMax,
        currency: "KSh",
        description: job.description,
        requirements: job.requirements,
        howToApply: job.howToApply,
        isRemote: job.isRemote || false,
        isFeatured: job.isFeatured || false,
        isUrgent: job.isUrgent || false,
        closingDate: job.closingDate ? new Date(job.closingDate) : null,
        employerId: employer.id,
        postedAt: new Date(Date.now() - Math.random() * 14 * 24 * 60 * 60 * 1000), // Random date within 14 days
      },
    });
  }

  // Create scholarships
  console.log("Creating scholarships...");
  for (const sch of scholarships) {
    await prisma.scholarship.create({
      data: {
        ...sch,
        deadline: sch.deadline ? new Date(sch.deadline) : null,
      },
    });
  }

  // Create articles
  console.log("Creating articles...");
  for (const art of articles) {
    await prisma.article.create({ data: art });
  }

  // Update category job counts
  console.log("Updating category job counts...");
  const jobCounts = await prisma.job.groupBy({
    by: ['category'],
    _count: { category: true },
  });
  for (const jc of jobCounts) {
    await prisma.category.updateMany({
      where: { name: jc.category },
      data: { jobCount: jc._count.category },
    });
  }

  console.log("Database seeded successfully!");
  console.log(`- ${createdEmployers.length} employers`);
  console.log(`- ${categories.length} categories`);
  console.log(`- ${jobs.length} jobs`);
  console.log(`- ${scholarships.length} scholarships`);
  console.log(`- ${articles.length} articles`);
}

seed()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
